### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by var1nthon** [alcheeee/Valorant-Object-Detection#2]
**My system:**
- OS: Windows 10 Pro 22H2 (OS build 19045.3757)
- CPU: AMD Ryzen 9 5900X @ 4.6 Ghz
- GPU: NVIDIA GeForce RTX 3060_12G
- RAM: 32G DDR4 @ 3200 MHz
- Monitor resolution: 2560 x 1440

Loading model\bestv8n.engine for TensorRT inference...
[04/16/2024-05:13:10] [TRT] [I] Loaded engine size: 17 MiB
[04/16/2024-05:13:11] [TRT] [E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
[04/16/2024-05:13:11] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\eel\__init__.py", line 318, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "C:\TEMP\Valorant-Object-Detection-main\application\utils\js_calls.py", line 60, in upload_file
    return picture_detection(original_file_path)
  File "C:\TEMP\Valorant-Object-Detection-main\application\utils\picture_predict.py", line 25, in picture_detection
    results = model_switch.model.predict(use_image,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\predictor.py", line 315, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\autobackend.py", line 188, in __init__
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by alcheeee** [comment]
Hi, that errors seems to be because of a mismatch between the TensorRT versions I used to train the models and the one you're using. For some reason I had completely forgotten to document which tensor version I was using.

Try installing tensorflow_gpu-2.8.0, cuDNN v8.1, CUDA v11.2. The project was also programmed in python 3.8.

[You can try here for more info if that doesn't work.](https://www.tensorflow.org/install/source_windows#download_the_tensorflow_source_code)


Let me know if I can help with anything else. I'll try to rebuild the project and update stuff later this week.
